apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-deployment
  labels:
    app: fiapslackpage
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fiapslackpage
  template:
    metadata:
      labels:
        app: fiapslackpage
    spec:
      containers:
        - name: fiapslackpage
            image: "USUARIO/fiap_slackpage"
          ports:
            - name: http
              containerPort: 80
          resources:
            limits:
              cpu: 0.2
              memory: "10Mi"
