#kubectl patch storageclass sc-default-portworx -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
kind: StorageClass
#apiVersion: storage.k8s.io/v1beta1
apiVersion: storage.k8s.io/v1
metadata:
    name: sc-default-portworx
    annotations:
        storageclass.kubernetes.io/is-default-class: true
provisioner: kubernetes.io/portworx-volume
parameters:
  repl: "2"
